# Generated by Django 5.0.3 on 2024-04-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desparacitacion',
            name='fecha',
            field=models.DateField(verbose_name='Fecha de Desparacitacion'),
        ),
    ]
