# Generated by Django 5.0.3 on 2024-04-11 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0002_alter_desparacitacion_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='edad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Edad de la Mascota'),
        ),
    ]
