# Generated by Django 5.0.3 on 2024-04-11 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0003_alter_mascota_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='fecha_consulta',
            field=models.DateTimeField(verbose_name='Fecha de consulta'),
        ),
    ]
